# 01 - Wczytywanie surowych danych i ich analiza

## Cel:

Wczytanie surowych danych meteorologicznych oraz danych o poziomie wody. Analiza ich struktury, zapoznanie się z danymi

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sys
import os
os.chdir('..')
print("Aktualny folder:", os.getcwd())

from src.data.dataset import build_meteo_dataframe, build_strzyza_level_dataframe, build_martwa_wisla_dataframe, build_port_polnocny_dataframe

Aktualny folder: /Users/majamarkiewicz/PycharmProjects/PortCanals

## Wczytywanie surowych danych meterologicznych

In [2]:
df_meteo_raw = build_meteo_dataframe()
print("Kształt danych:", df_meteo_raw.shape)
df_meteo_raw.head()

Kształt danych: (43680, 5)

               Data Opad [mm] Temperatura [C] Wilgotność [%] Ciśnienie [hPa]
0  2025-07-01 00:00         0            14.8             76          1016.2
1  2025-07-01 01:00         0            14.6           74.2          1016.3
2  2025-07-01 02:00         0            14.9           67.8          1016.2
3  2025-07-01 03:00         0            14.9           64.1          1016.4
4  2025-07-01 04:00         0              15           59.4          1016.5

In [3]:
df_meteo_raw.tail()

,Data,Opad [mm],Temperatura [C],Wilgotność [%],Ciśnienie [hPa]
4412,2021-12-31 19:00,0,9.4,87.5,1002.5
4413,2021-12-31 20:00,0,8.9,88.4,1003.4
4414,2021-12-31 21:00,0,8.4,88.3,1004
4415,2021-12-31 22:00,0,8.1,86.7,1004.4
4416,2021-12-31 23:00,0,8,87.2,1004.8

In [4]:
df_meteo_raw.info()

<class 'pandas.DataFrame'>
Index: 43680 entries, 0 to 4416
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data             43680 non-null  str
 1   Opad [mm]        43680 non-null  object
 2   Temperatura [C]  43680 non-null  object
 3   Wilgotność [%]   43680 non-null  object
 4   Ciśnienie [hPa]  43680 non-null  object
dtypes: object(4), str(1)
memory usage: 2.0+ MB

In [5]:
df_meteo_raw.describe()

,Data,Opad [mm],Temperatura [C],Wilgotność [%],Ciśnienie [hPa]
count,43680,43680,43680,43680,43680
unique,43675,396,507,796,708
top,2025-10-26 02:00,0,-,-,-
freq,2,40048,433,433,433

## Wczytywanie surowych danych poziomu wody strugi strzyża

In [6]:
df_strzyza_level_raw = build_strzyza_level_dataframe()
print("Kształt danych:", df_strzyza_level_raw.shape)
df_strzyza_level_raw.head()

Kształt danych: (43672, 2)

               Data Poziom wody [m]
0  2025-07-01 00:00            0.34
1  2025-07-01 01:00            0.32
2  2025-07-01 02:00            0.33
3  2025-07-01 03:00            0.32
4  2025-07-01 04:00            0.32

In [7]:
df_strzyza_level_raw.tail()

                  Data Poziom wody [m]
4412  2021-12-31 19:00            0.05
4413  2021-12-31 20:00            0.08
4414  2021-12-31 21:00            0.01
4415  2021-12-31 22:00            0.05
4416  2021-12-31 23:00            0.09

In [8]:
df_strzyza_level_raw.info()

<class 'pandas.DataFrame'>
Index: 43672 entries, 0 to 4416
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data             43672 non-null  str
 1   Poziom wody [m]  43672 non-null  object
dtypes: object(1), str(1)
memory usage: 1023.6+ KB

In [9]:
df_strzyza_level_raw.describe()

                    Data  Poziom wody [m]
count              43672         43672.00
unique             43667           171.00
top     2025-10-26 02:00             0.14
freq                   2          1201.00

## Wczytywanie surowych danych poziomu wody Martwej rzeki

In [10]:
df_martwa_raw = build_martwa_wisla_dataframe()
print("Kształt danych:", df_martwa_raw.shape)
df_martwa_raw.head()

Kształt danych: (43608, 2)

               Data Poziom wody [m]
0  2021-01-01 00:00           -0.28
1  2021-01-01 01:00           -0.28
2  2021-01-01 02:00           -0.25
3  2021-01-01 03:00           -0.25
4  2021-01-01 04:00           -0.25

In [11]:
df_martwa_raw.tail()

                   Data Poziom wody [m]
43603  2025-12-31 19:00            0.13
43604  2025-12-31 20:00            0.14
43605  2025-12-31 21:00            0.15
43606  2025-12-31 22:00            0.16
43607  2025-12-31 23:00            0.15

In [12]:
df_martwa_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 43608 entries, 0 to 43607
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data             43608 non-null  str
 1   Poziom wody [m]  43608 non-null  object
dtypes: object(1), str(1)
memory usage: 681.5+ KB

In [13]:
df_martwa_raw.describe()

                    Data Poziom wody [m]
count              43608           43608
unique             43603             167
top     2021-10-31 02:00               -
freq                   2            1483

## Wczytywanie surowych danych poziomu wody z Portu północnego

In [14]:
df_port_raw = build_port_polnocny_dataframe()
print("Kształt danych:", df_port_raw.shape)
df_port_raw.head()

Kształt danych: (43673, 2)

               Data Poziom wody [m]
0  2021-01-01 00:00            5.03
1  2021-01-01 01:00            5.03
2  2021-01-01 02:00            5.05
3  2021-01-01 03:00            5.05
4  2021-01-01 04:00            5.04

In [15]:
df_port_raw.tail()

                   Data Poziom wody [m]
43668  2025-12-31 19:00            5.27
43669  2025-12-31 20:00             5.3
43670  2025-12-31 21:00            5.31
43671  2025-12-31 22:00             5.3
43672  2025-12-31 23:00            5.29

In [16]:
df_port_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 43673 entries, 0 to 43672
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data             43673 non-null  str
 1   Poziom wody [m]  43673 non-null  object
dtypes: object(1), str(1)
memory usage: 682.5+ KB

In [17]:
df_port_raw.describe()

                    Data Poziom wody [m]
count              43673           43673
unique             43668             175
top     2021-10-31 02:00               -
freq                   2            2336

## Wnioski i Obserwacje dotyczące surowych danych

### Dane meteorologiczne

- Dane mają **43 680 wierszy** w kroku godzinowym
- Występuje **5 kolumn**, Data, Opad, Temperature, Wilgotność, Ciśnienie
- Daty pochodzą z zakresu 2021-2025
- Kolumny będzie trzeba poddać konwersji (object -> liczby)

### Dane poziomu wody - Strzyża

- Dane mają **43 672 wierszy** w kroku godzinowym
- Daty pochodzą także z zakresu 2021-2025
- Kolumne będzie trzeba poddać konwersji (object -> liczby)

### Dane poziomu wody - Martwa Wisła

- Dane mają **43 608 wierszy** w kroku godzinowym
- Zakres dat: 2021-2025
- Poziom wody w zakresie około -0.28m do 0.16m
- Kolumna wymaga konwersji (object → liczby)

### Dane poziomu wody - Port Północny

- Dane mają **43 673 wierszy** w kroku godzinowym
- Zakres dat: 2021-2025
- Poziom wody w zakresie około 5.0m - 5.3m (wyższy poziom odniesienia niż pozostałe stacje)
- Kolumna wymaga konwersji (object → liczby)

### Dalsze Decyzje

- Dane będą czyszczone przez usunięcie fizycznie nie możliwych wartości
- Nastąpi agregacja do kroku dobowego
- Braki zostaną uzupełnione medianą sezonową
- Wszystkie trzy stacje poziomu wody zostaną połączone z danymi meteorologicznymi po dacie